const SUPABASE_URL = 'https://bncjcvvqmrenlfwrmozw.supabase.co'
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJuY2pjdnZxbXJlbmxmd3Jtb3p3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA5NTA3NDksImV4cCI6MjA5NjUyNjc0OX0.NsFTqkLKeOMWy3OjRtADZXw8fl31mE5eqTdHYNfHk_4'
const db = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY)
